AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: service.handler
      Runtime: python3.6
      CodeUri: lambda.py
      Environment:
        Variables:
          BUCKET: !Ref Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Mthod: post
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
          - s3:PutObjectAcl
          Resource:
          - !Sub 'arn:aws:s3:::${BucketName}'
          - !Sub 'arn:aws:s3:::${BucketName}/*'
Outputs:
  Website:
    Description: S3 website URL
    Value: !GetAtt Bucket.WebsiteURL
